---
  - name: setup nginx.conf
    template:
      src: nginx.conf
      dest: /etc/nginx/nginx.conf
      owner: nginx
      group: nginx
      mode: 644

  - name: enable nginx
    service: name=nginx enabled=yes state=started
