---
  - name: create log and pid directories for gunicorn
    file: 
      path: "{{ item }}"
      owner: "{{ webapp_user }}"
      group: "{{ webapp_user }}"
      mode: 755
      state: directory
    with_items:
      - /var/log/gunicorn
      - /run/gunicorn

  - name: create systemd gunicorn directory
    file: 
      path: "{{ gunicorn_dir }}"
      owner: root
      group: root
      mode: 0755
      state: directory

  - name: add gunicorn systemd service
    template: src=gunicorn.service dest="{{ gunicorn_dir }}/gunicorn.service"
    register: gunicorn

  - name: add gunicorn systemd socket
    template: src=gunicorn.socket dest="{{ gunicorn_dir }}/gunicorn.socket"

  - name: reload systemd when changed
    systemd:
      daemon_reload: yes
      name: gunicorn.service
      state: restarted
    when: gunicorn.changed
