---
  - name: base-playbook
    hosts: webservers
    roles:
      - { role: base_additions, tags: base_additions }
      - { role: users, tags: users }
      - { role: gunicorn, tags: gunicorn }
      - { role: nginx, tags: nginx }
    become: true
