---
  - name: clone webapp
    git:
      repo: https://github.com/philbert/sample_flask_app.git
      dest: "{{ webapp_dir }}"

  - name: setup virtualenv for webapp
    pip:
      requirements: "{{ webapp_dir }}/requirements.txt"
      virtualenv: "{{ webapp_root }}/virtenv"

        
