---
  - name: Create webapp group
    group: name="{{ webapp_user }}" 

  - name: Create webapp user
    user: 
      name: "{{ webapp_user }}" 
      shell: /bin/bash
      group: "{{ webapp_user }}"
      home: "{{ webapp_dir }}"
      createhome: no

  - name: create the webapp root
    file: 
      path: "{{ webapp_root }}"
      owner: "{{ webapp_user }}"
      group: "{{ webapp_user }}" 
      mode: 0755
      state: directory
