---
  - name: update and upgrade base packages
    apt: 
      upgrade: dist
      update_cache: yes
    become: true

  - name: install base packages
    package:
      name: "{{ item }}"
      state: latest
    with_items:
      - python-pip
      - ntpdate
      - git

  - name: install virtualenv
    pip:
      name: "{{ item }}"
    with_items:
      - virtualenv


