---
  - name: update and upgrade base packages
    apt: 
      upgrade: dist
      update_cache: yes

  - name: install base packages
    package:
      name: "{{ item }}"
      state: latest
    with_items:
      - python3-pip
      - ntpdate
      - git
      - nginx 

  - name: install virtualenv
    pip:
      name: "{{ item }}"
    with_items:
      - virtualenv


